/vis/open OGL 600x600-0+0

/vis/viewer/set/autoRefresh false
/vis/verbose errors

/vis/drawVolume

/vis/viewer/set/viewpointThetaPhi 90. 180.
/vis/viewer/zoom 1.7
/vis/viewer/set/globalLineWidthScale 2
/vis/viewer/rebuild

/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
##/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
##/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
/vis/modeling/trajectories/drawByCharge-0/set 0 green
/vis/modeling/trajectories/drawByCharge-0/set 1 blue
/vis/modeling/trajectories/drawByCharge-0/set -1 blue

/vis/filtering/trajectories/create/attributeFilter
/vis/filtering/trajectories/attributeFilter-0/setAttribute IMag
/vis/filtering/trajectories/attributeFilter-0/addInterval 10 GeV 10000 GeV

##http://www.apc.univ-paris7.fr/~franco/g4doxy/html/classG4TrajectoryDrawByParticleID.html
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/filtering/trajectories/create/chargeFilter
#/vis/filtering/trajectories/chargeFilter-0/add 1
#/vis/filtering/trajectories/chargeFilter-0/add -1

/vis/scene/endOfEventAction accumulate

/vis/viewer/set/autoRefresh true
/vis/verbose warnings

/vis/reviewKeptEvents
